# Generated by Django 5.2.11 on 2026-09-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0015_ensure_camera_purposes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='resolution',
            field=models.CharField(blank=True, default='3840x2160', max_length=32),
        ),
    ]
